/**
 * Shared enumeration of all TCP actions mapped between the Gateway and TCP Server.
 */
export const ACTIONS = {
  // Auth Actions
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_VERIFY_2FA: 'AUTH_VERIFY_2FA',
  AUTH_RESEND_OTP: 'AUTH_RESEND_OTP',

  // User Actions
  USER_GET_ME: 'USER_GET_ME',

  // API Key Actions
  API_KEY_CREATE: 'API_KEY_CREATE',
  API_KEY_LIST: 'API_KEY_LIST',
  API_KEY_REVOKE: 'API_KEY_REVOKE',

  // Transaction Actions
  TRANSACTION_CHECKOUT: 'TRANSACTION_CHECKOUT',
  TRANSACTION_GET_BY_ID: 'TRANSACTION_GET_BY_ID',
  TRANSACTION_GET_USER_TRANSACTIONS: 'TRANSACTION_GET_USER_TRANSACTIONS',
};
