/**
 * Shared enumeration of all TCP actions mapped between the Gateway and TCP Server.
 */
export const ACTIONS = {
  // Auth Actions
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_VERIFY_2FA: 'AUTH_VERIFY_2FA',
  AUTH_RESEND_OTP: 'AUTH_RESEND_OTP',

  // User Actions
  USER_GET_ME: 'USER_GET_ME',

  // API Key Actions
  API_KEY_CREATE: 'API_KEY_CREATE',
  API_KEY_LIST: 'API_KEY_LIST',
  API_KEY_REVOKE: 'API_KEY_REVOKE',

  // Product Actions
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_GET_BY_ID: 'PRODUCT_GET_BY_ID',
  PRODUCT_GET_ME: 'PRODUCT_GET_ME',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  // Wallet Actions
  WALLET_DEPOSIT: 'WALLET_DEPOSIT',
  WALLET_WITHDRAW: 'WALLET_WITHDRAW',
};
